-- +goose Up
CREATE TABLE USERS (
  ID UUID PRIMARY KEY,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  NAME VARCHAR(30) NOT NULL
);

-- +goose Down
DROP TABLE USERS;
